name: PR build
on:
  pull_request
env:
  REALM_DISABLE_ANALYTICS: true
  DOTNET_NOLOGO: true
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build packages
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Register csc problem matcher
        run: echo "::add-matcher::.github/problem-matchers/csc.json"
      - name: Register msvc problem matcher
        run: echo "::add-matcher::.github/problem-matchers/msvc.json"
      - name: Set version suffix
        id: set-version-suffix
        #! Build suffix is pr-1234.5 for pr builds or alpha.123 for branch builds.
        run: |
          $suffix=""
          if ($env:GITHUB_EVENT_NAME -eq "pull_request")
          {
            if (-Not "${{ github.head_ref }}".Contains("release"))
            {
              $suffix = "pr-${{ github.event.number }}.$env:GITHUB_RUN_NUMBER"
            }
          }
          else
          {
            $suffix = "alpha.$env:GITHUB_RUN_NUMBER"
          }
          echo "build_suffix=$suffix" >> $Env:GITHUB_OUTPUT
        shell: pwsh
      - name: Build packages
        run: |
          dotnet build Realm.LFS -restore
          dotnet pack Realm.LFS -p:VersionSuffix=${{ steps.set-version-suffix.outputs.build_suffix }}
          dotnet build Realm.LFS.Azure -restore
          dotnet pack Realm.LFS.Azure -p:VersionSuffix=${{ steps.set-version-suffix.outputs.build_suffix }}
          dotnet build Realm.LFS.S3 -restore
          dotnet pack Realm.LFS.S3 -p:VersionSuffix=${{ steps.set-version-suffix.outputs.build_suffix }}
          dotnet build Realm.LFS.Functions -restore
          dotnet pack Realm.LFS.Functions -p:VersionSuffix=${{ steps.set-version-suffix.outputs.build_suffix }}
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: ${{ github.workspace }}/packages/*
          retention-days: ${{ github.event_name != 'pull_request' && 30 || 1 }}
          if-no-files-found: error
